name: Docker Image

on:
  push:
    branches:
      - develop
      - COV-662-create-docker-image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: praekeltfoundation/ndoh-jsbox
          dockerfile: node_12.x.dockerfile
          tag_with_ref: true
          tag_with_sha: true
